//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2_Apollo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuestionID { get; set; }
        public string UserQuestionOne { get; set; }
        public string AnswerOne { get; set; }
        public string UserQuestionTwo { get; set; }
        public string AnswerTwo { get; set; }
        public string UserQuestionThree { get; set; }
        public string AnswerThree { get; set; }
        public Nullable<int> FUserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
